name: Testing Config Variables

on:
  workflow_dispatch:

env:
  CLOUD: google-cld

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      GREETING: Hola
    steps:
      - name: Say hi and print project ID
        env:
          FIRST_NAME: Keith
        run: |
          echo "hi $FIRST_NAME"
          echo "${{ vars.PROJECT_ID }}"
