name: Testing Config Variables

on:
  workflow_dispatch:

env:
  CLOUD: google-cld

jobs:
  greeting_job:
    runs-on: ubuntu-latest

    env:
      GREETING: Hola

    steps:
      - name: Say hi
        env:
          FIRST_NAME: Keith

        run: echo "$GREETING $FIRST_NAME w project: ${{ vars.PROJECT_ID }}"
