name: Testing Config Variables

on:
  workflow_dispatch

env:
  cloud: google-cld

jobs:
  greeting_job:
    runs-on: ubuntu_latest
  env:
    Greeting: Hola
  steps:
    - name: "Say hi"
      run: echo "$Greeting $FirstName w project: ${{vars.PROJECT_ID}}"
      
      env:
        First_Name: Keith
