name: Testing Context Variables

on:
  workflow_dispatch:

env:
  CLOUD: google-cld

jobs:
  test_context:
    runs-on: ubuntu-latest
    env:
      GREETING: Hola
    steps:
      - name: "Checking Context var"
        run: |
          echo "repo: ${{ github.repository }}"
          echo "workflow: ${{ github.workflow }}"
          echo "actor: ${{ github.triggering_actor }}"
