name: Testing Variables

on:
  workflow_dispatch: # <--- THIS ENABLES THE "RUN WORKFLOW" BUTTON
  workflow_run:
    workflows: ["Your Main Workflow Name Here"]
    types: [completed]

env:
  cloud: google-cloud

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "say on monday"
        run: echo "say hi"
